kind: pipeline
type: docker
name: default

steps:
  - name: build and run
    image: docker
    environment:
      ENV_FILE:
        from_secret: ENV_FILE
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - echo "$ENV_FILE" > .env
      - docker build -t my-web-app:${DRONE_BUILD_NUMBER} .
      - docker stop my-web-app || true
      - docker rm my-web-app || true
      - docker run -d \
          --name my-web-app \
          --env-file .env \
          -p 8000:3000 \
          my-web-app:${DRONE_BUILD_NUMBER}

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
