name: Build docker app

on:
  push:
    branches:
      - main
  workflow_dispatch:
    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: install dependencies
        run: |
          bun install

      - name: Build docker
        run: |
          docker build -t portofolio-api:latest
      
      - name: Export docker image
        run: |
          mkdir -p /opt/myapps
          docker save portofolio-api:latest -o /opt/myapps/portofolio-api.tar