name: Build docker app

on:
  push:
    branches:
      - main
  workflow_dispatch: {}
    

jobs:
  build:
    runs-on: debian-custom
    steps:
      - name: Checkout code
        run: |
          git init
          git remote add origin $GITHUB_SERVER_URL/$GITHUB_REPOSITORY.git
          git fetch --depth=1 origin $GITHUB_SHA
          git checkout FETCH_HEAD

      - name: Build docker
        run: |
          IMAGE_NAME="${GITEA_REPO_NAME}:${GITEA_WORKFLOW_SHA}"
          docker build -t $IMAGE_NAME .
      
      - name: Export docker image
        run: |
          mkdir -p /opt/myapps/${GITEA_REPOSITORY}
          IMAGE_NAME="${GITEA_REPO_NAME}:${GITEA_WORKFLOW_SHA}"
          docker save portofolio-api:latest -o /opt/myapps/$GITEA_REPOSITORY/$IMAGE_NAME.tar

      - name: Notify
        run: |
          IMAGE_NAME="${GITEA_REPO_NAME}:${GITEA_WORKFLOW_SHA}"
          echo "Saved success /opt/myapps/${GITEA_REPOSITORY}/${IMAGE_NAME}.tar}"