name: Build docker app

on:
  push:
    branches:
      - main
  workflows_dispatch: {}
    

jobs:
  build:
    runs-on: debian-custom
    steps:
      - name: Checkout code
        run: |
          git init
          git remote add origin $GITHUB_SERVER_URL/$GITHUB_REPOSITORY.git
          git fetch --depth=1 origin $GITHUB_SHA
          git checkout FETCH_HEAD
        
      - name: install dependencies
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env
          bun install

      - name: build app
        run: |
          bun run build

      - name: Build docker
        run: |
          docker build -t portofolio-api:latest .
      
      - name: Export docker image
        run: |
          mkdir -p /opt/myapps
          docker save portofolio-api:latest -o /opt/myapps/portofolio-api.tar 