name: Deploy to Capistrano

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to production
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup SSH
        uses:  appleboy/ssh-action@v1.1.0
        with:
          key: ${{ secrets.SERVER_SSH_KEY }}
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            bash /home/${{ secrets.SERVER_USER }}/scripts/deploy.sh
